import Section3Bg from "@/assets/images/home/Section3-bg.png";
import CrossIcon from "@/assets/images/home/cross.png";
import React from "react";

const Section3 = () => {
  return (
    <div className="text-center relative flex flex-col md:flex-row justify-center pt-[36px] max-md:px-[26px] md:pt-[150px]">
      <div style={{
        backgroundImage: `url(${CrossIcon})`,
        backgroundSize: "contain",
        backgroundRepeat: 'no-repeat',
        backgroundPosition: "center"
      }} className="w-full bg-black md:w-[39.4vw] object-contain">
      </div>
      {/* <img alt="" src={CrossIcon} className="w-full bg-black md:w-[39.4vw] object-contain"></img> */}
      <div className="border-[1px] max-md:mt-[-47px] md:ml-[-3vw] z-[1] bg-black shrink-0 text-left w-full md:w-[42.6vw] px-[14px] md:px-[80px] py-[17px] md:py-[52px] border-[#4E4E4EE6] rounded-[8px] relative">
        <img
          src={Section3Bg}
          alt=""
          className="w-full max-md:hidden aspect-[1636/355] absolute left-0 top-0"
        />
        <div className="text-left text-[19.33px] z-[1] relative md:text-[48px] after:absolute after:top-[14.5px] md:after:top-[34.5px] after:bg-gradient-to-r after:from-[#4F74CA] after:to-[#9129DC] after:w-[205px] max-md:text-center md:after:w-[320.5px] after:z-[-1] after:left-[calc(50%-102.5px)] md:after:left-[0px] after:h-[8px] md:after:h-[12.5px] inline-block leading-[21px] md:leading-[47.5px]">
          Cross-chain stablecoin with native yield
        </div>
        <div className="text-[12px] md:text-[15px] mt-[18px] md:mt-[59.5px] text-[#BFBFBF] text-left font-[Inter] leading-[16px] md:leading-[25.9px]">
          muUSD is issued through a 1:1 collateralization with USDC deposited in
          the Mullex Bridge. muUSD can be staked in Mullex Saving{" "}
          <span className="text-[12px] md:text-[14.5px] leading-[12px] px-[4px] md:px-[6.5px] md:py-[1px] text-[#000000] bg-[#C0C0C0] rounded-[5px]">
            1
          </span>{" "}
          to earn continuous profits, with yields derived from the LP profits of
          USDC in the Mullex Bridge. Users can also stake muUSD to obtain the
          LST token lsUSD and participate in DeFi activities. In the future,
          muUSD will serve as an aggregator for a basket of USD
          stablecoins,supporting various community-recognized stablecoins,
          including USDC, USDT, USD0, and more{" "}
          <span className="text-[12px] md:text-[14.5px] leading-[12px] px-[4px] md:px-[6.5px] md:py-[1px] text-[#000000] bg-[#C0C0C0] rounded-[5px]">
            2
          </span>{" "}
          .
        </div>
        <div className="mt-[16px] text-[10px] font-[Inter] leading-[15px] text-[#5F5D5D] md:hidden">
          <div className="flex items-baseline">
            <div className="text-[8px] w-[10px] shrink-0 flex items-center justify-center mr-1 h-[10px] text-[#000000] bg-[#5F5F5F] rounded-[2px]">
              1
            </div>{" "}
            Mullex Saving will launch in Q4 2025, and prior to its launch, the
            profits generated by muUSD will be held in a DAO account. The
            specific profit distribution method will be announced later.
          </div>{" "}
          <div className="mt-[14px] flex items-baseline">
            <div className="text-[8px] w-[10px] shrink-0 flex items-center justify-center mr-1 h-[10px] text-[#000000] bg-[#5F5F5F] rounded-[2px]">
              2
            </div>{" "}
            Whether to introduce additional stablecoins to diversify muUSD will
            be decided by community governance. As of now, muUSD is 100% backed
            by USDC.
          </div>
        </div>
        <div className="flex flex-wrap gap-[16px] md:gap-[22px] flex-col md:flex-row mt-[20px] md:mt-[39.5px] text-[14px] md:text-[16px] items-center">
          <div onClick={() => window.open("https://mullex.gitbook.io/mullex-docs/")} className="max-md:w-full justify-center flex items-center border-[1px] border-[#ffffff] rounded-[8px] h-[40px] md:h-[42px] px-[18px] shrink-0 cursor-pointer hover:bg-[#4A4A4A] transition-opacity">
            Learn More
          </div>
          <div onClick={() => window.open("https://bridge.mullex.io/muUSD")} className="max-md:w-full justify-center bg-gradient-to-t flex items-center from-[#9A1FDE] to-[#04C9B7] rounded-[8px] shrink-0 h-[40px] md:h-[42px] px-[18px] cursor-pointer hover:from-[#4F74CA] hover:to-[#4F74CA] transition-opacity">
            Mint muUSD
          </div>
          <div className="max-md:w-full justify-center flex items-center border-[1px] border-[#ffffff] rounded-[8px] h-[40px] md:h-[42px] px-[18px] shrink-0 cursor-pointer hover:bg-[#4A4A4A] transition-opacity">
            Request for integration
          </div>
        </div>
        <div className="pt-[32.5px] max-md:hidden border-t-[1px] border-[#4D4D4D] text-[14px] font-[Inter] leading-[24.3px] text-[#5F5D5D] mt-[36.5px]">
          <div className="flex items-baseline">
            <div className="text-[12px] w-[16px] shrink-0 flex items-center justify-center mr-1 h-[16px] text-[#000000] bg-[#5F5F5F] rounded-[4px]">
              1
            </div>{" "}
            Mullex Saving will launch in Q4 2025, and prior to its launch, the
            profits generated by muUSD will be held in a DAO account. The
            specific profit distribution method will be announced later.
          </div>{" "}
          <div className="mt-[25.5px] flex items-baseline">
            <div className="text-[12px] w-[16px] shrink-0 flex items-center justify-center mr-1 h-[16px] text-[#000000] bg-[#5F5F5F] rounded-[4px]">
              2
            </div>{" "}
            Whether to introduce additional stablecoins to diversify muUSD will
            be decided by community governance. As of now, muUSD is 100% backed
            by USDC.
          </div>
        </div>
      </div>
    </div>
  );
};

export default React.memo(Section3);

